[package]
name = "reaction-trainer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.4"
rand = "0.8.3"
lazy_static = "1.4.0"